# Generated by Django 5.0.6 on 2024-07-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chat_user_alter_userprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(default='new_chat', max_length=150),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
