# Generated by Django 5.0.6 on 2024-08-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_model_chatmemory_gpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmemory',
            name='gpt',
            field=models.TextField(blank=True),
        ),
    ]
