# Generated by Django 5.0.6 on 2024-08-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chatmemory_gpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmemory',
            name='gpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmemory',
            name='member',
            field=models.TextField(blank=True, null=True),
        ),
    ]
